### ISSUE TITLE
the wording.get call inside velocity vm file just been outputted as raw

### ISSUE THREAD

**Issue by fuyinhai** [qalingo/qalingo-web-classic-fo-bo#38]
Hi, Thanks for create this great product. I successfully able to run the product and met a minor problem as:

1> checkout the modules for version 0.9.0:
    qalingo-assets			
    qalingo-i18n			
    qalingo-shared			
    qalingo-engine			
    qalingo-quick-start-linux-env	
    qalingo-web-classic-fo-bo
2> make a full build
3> by following the get-started docs I deployed the bo-business and bo-business-resources
4> I able to see the login page and everything goes well
5> the problem is all the $wording.get just been outputted as raw e.g. the HTML source code outputed on screen: $wording.get("bo.header_menu.marketplace")
6> Am I missed anything?

Thanks for your help

**Comment by dgosset** [comment]
You're right. We broke some parts, we are working on a major refactoring for Spring4/Java8/Ehcache3.
I have just commit a fix on the 0.9.1-SNAPSHOT (git origin). Use this version, 0.9.0 was corrupted by jenkins (auto build/release).
